//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GP
    {
        public GP()
        {
            this.Hospitals = new HashSet<Hospital>();
            this.Patients = new HashSet<Patient>();
        }
    
        public int GPID { get; set; }
        public string GPFirstname { get; set; }
        public string GPSurname { get; set; }
        public string GPNumber { get; set; }
    
        public virtual ICollection<Hospital> Hospitals { get; set; }
        public virtual ICollection<Patient> Patients { get; set; }
    }
}
