//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hospital
    {
        public int HospitalID { get; set; }
        public int GPID { get; set; }
        public int CallCentreID { get; set; }
        public string HospitalName { get; set; }
        public string Town { get; set; }
        public string City { get; set; }
        public string Conty { get; set; }
        public string Country { get; set; }
    
        public virtual CallCentre CallCentre { get; set; }
        public virtual GP GP { get; set; }
    }
}
