//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MedicationHistory
    {
        public int MedicationHistoryID { get; set; }
        public int PatientID { get; set; }
        public string MedicationHistory1 { get; set; }
        public string Medication { get; set; }
        public string Alergies { get; set; }
    
        public virtual Patient Patient { get; set; }
    }
}
