//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patient
    {
        public Patient()
        {
            this.MedicationHistories = new HashSet<MedicationHistory>();
            this.Medications = new HashSet<Medication>();
        }
    
        public int PatientID { get; set; }
        public int MedicationID { get; set; }
        public int GPID { get; set; }
        public string Firstname { get; set; }
        public string Surname { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string Address3 { get; set; }
        public System.DateTime DOB { get; set; }
        public string Medication { get; set; }
        public string MedicationInfo { get; set; }
        public Nullable<double> lat { get; set; }
        public Nullable<double> lon { get; set; }
    
        public virtual GP GP { get; set; }
        public virtual ICollection<MedicationHistory> MedicationHistories { get; set; }
        public virtual PatientCall PatientCall { get; set; }
        public virtual ICollection<Medication> Medications { get; set; }
    }
}
